# Generated by Django 4.2.2 on 2023-07-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='Address_pep',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profil',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
