# Generated by Django 4.2.2 on 2023-08-12 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_profil_id_alter_profil_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catolog',
            name='id_catolog',
        ),
        migrations.AlterField(
            model_name='product',
            name='id_catolog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.catolog'),
        ),
    ]
