# Generated by Django 4.2.1 on 2023-09-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_order_product_product_block_o'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_block_o',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
